### PR TITLE
Add necessary steps for spinnaker deployments

### PR DESCRIPTION
**Pull request by smaslennikov**

### CODE REVIEW

**Comment by smaslennikov** [comment]
@raddaoui @naftulikay here we go

**Comment by smaslennikov** [comment]
@naftulikay this is ready for review, though I can't add you as a reviewer, lacking permissions.

**Comment by naftulikay** [comment]
@smaslennikov can you squash?

**Comment by naftulikay** [comment]
also @smaslennikov can you move all the Spinnaker related files to like a prefix? maybe `demos/spinnaker` or something like that.

**Comment by smaslennikov** [comment]
@naftulikay done. Please review and merge as ready.

**Comment by naftulikay** [comment]
Allowing a multi-commit PR this one time. In the future, let's stick to one final commit to merge in each PR.

**Pull request merged**
